### ISSUE TITLE
Output of "spacialdb db" CLI command is hardly readable

### ISSUE THREAD

**Issue by vovayartsev** [decision-labs/spacialdb-devcenter#1]
In Linux shell:

$ spacialdb db
namespacialdb0_itsspccreated_at2011-07-05 09:46:40 +0000updated_at2011-07-05 09:46:40 +0000port9999usernameitsspcid74user_id27hostbeta.spacialdb.compasswordXXXXXXX

The output above is hardly readable.

PS: I'm not sure where to post issues, so I posted it here.

**Comment by booo** [comment]
Please don't publish your password ;)

With gem version 0.0.2 on ubuntu the output should be a json string.

**Comment by vovayartsev** [comment]
Thanks :-) Didn't notice the password :-)

I'm on Ubuntu, and  "spacialdb version" command says "spacialdb-gem/0.0.2"
